version: '3.4'

services:
  ui:
    container_name: ui_container
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile

  api:
    container_name: api_container
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

networks:
  default:
    external:
        name: ElementsNetwork
