version: '3.4'

services:
  ui:
    container_name: ui_container
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - "49161:443"
  api:
    container_name: api_container
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "49162:443"